 <!-- Navigation -->
    <nav class="main-menu">
    	
        <ul>
            <li id="tag"><a href="http://www.urcsc174.org/xli62/project3/">Xingyi Li</a></li>
            <li><a href="http://www.urcsc174.org/xli62/project3/index.php">Home</a></li>
            <li><a href="http://www.urcsc174.org/xli62/project3/index.php#second">Accomplishments</a></li>
            <li><a href="http://www.urcsc174.org/xli62/project3/portfolio.php">Portfolio</a></li>
            <li><a href="http://www.urcsc174.org/xli62/project3/html-form.php">Contact form</a></li>
        </ul>

    </nav>